# Generated by Django 3.2.6 on 2021-08-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('jewellery', 'jewellery'), ('graphic', 'graphic'), ('photography', 'photography'), ('fine art', 'fine art'), ('other', 'other')], default='other', max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
