# Generated by Django 3.2.6 on 2021-08-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0005_alter_art_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
