# Generated by Django 3.2.6 on 2021-08-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='date',
        ),
        migrations.AddField(
            model_name='topics',
            name='topic_type',
            field=models.CharField(choices=[('jewellery', 'jewellery'), ('graphic', 'graphic'), ('photography', 'photography'), ('fine art', 'fine art'), ('other', 'other')], default='other', max_length=25),
        ),
    ]
